
version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: app/dev.Dockerfile
    container_name: multiplayer_app
    ports:
      - 9000:9000
    environment:
        PORT: 9000
    volumes:
      - ./app:/usr/app
  server:
    build:
      context: .
      dockerfile: server/dev.Dockerfile
    container_name: multiplayer_server
    ports:
      - 4000:4000
    environment:
        PORT: 4000
    volumes:
      - ./server:/server