
version: "3.8"
services:
  server:
    build:
      context: .
      dockerfile: server/dev.Dockerfile
    container_name: multiplayer_server
    ports:
      - 4000:4000
    environment:
        PORT: 4000
    volumes:
      - ./server:/server